services:
  - type: web
    name: controla-senhas
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_USE_SQLITE
        value: false
      - key: DB_HOST
        sync: false # Você configurará isso no dashboard
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: SESSION_SECRET
        generateValue: true # Isso gerará uma string aleatória segura
